// SVG
export const ACCOMMODATION_ICON_SVG = "/svg/accommodation-icon.svg"
export const ATTRACTION_ICON_SVG = "/svg/attraction-icon.svg"
export const FACEBOOK_ICON_SVG = "/svg/facebook-icon.svg"
export const INSTAGRAM_ICON_SVG = "/svg/instagram-icon.svg"
export const TIKTOK_ICON_SVG = "/svg/tiktok-icon.svg"
export const LAUNDRY_ICON_SVG = "/svg/laundry-icon.svg"
export const PLANE_ICON_SVG = "/svg/plane-icon.svg"
export const TOWEL_ICON_SVG = "/svg/towel-icon.svg"
export const MEALS_ICON_SVG = "/svg/meals-icon.svg"
export const TRANSPORTATION_ICON_SVG = "/svg/transportation-icon.svg"
export const WHATSAPP_ICON_SVG = "/svg/whatsapp-icon.svg"
export const YOUTUBE_ICON1_SVG = "/svg/youtube-icon1.svg"
export const YOUTUBE_ICON2_SVG = "/svg/youtube-icon2.svg"
export const FLIGHT_ICON_SVG = "/svg/flight-icon.svg"

export const BRASIL_FLAG_SVG = "/svg/brasil-flag.svg"
export const FRENCH_FLAG_SVG = "/svg/french-flag.svg"
export const ISRAEL_FLAG_SVG = "/svg/israel-flag.svg"
export const JORDAN_FLAG_SVG = "/svg/jordan-flag.svg"
export const RUSSIAN_FLAG_SVG = "/svg/russian-flag.svg"
export const SPANISH_FLAG_SVG = "/svg/spanish-flag.svg"
export const USA_FLAG_SVG = "/svg/usa-flag.svg"
export const GERMAN_FLAG_SVG = "/svg/german-flag.svg"

export const LOGO_FOOTER_SVG = "/svg/logo-footer.svg"
export const LOGO_WHITE_SVG = "/svg/logo-white.svg"
export const LOGO_SVG = "/svg/logo.svg"

export const FLOWER1_SVG = "/svg/flower1.svg"
export const FLOWER2_SVG = "/svg/flower2.svg"
export const FLOWER_RIGHT1_SVG = "/svg/flower-right1.svg"
export const FLOWER_RIGHT2_SVG = "/svg/flower-right2.svg"
export const FLOWER_RIGHT3_SVG = "/svg/flower-right3.svg"
export const FLOWER_RIGHT4_SVG = "/svg/flower-right4.svg"
export const FLOWER_LEFT1_SVG = "/svg/flower-left1.svg"
export const FLOWER_LEFT2_SVG = "/svg/flower-left2.svg"
export const FLOWER_LEFT3_SVG = "/svg/flower-left3.svg"
export const FLOWER_LEFT4_SVG = "/svg/flower-left4.svg"

export const PLANE1_SVG = "/svg/plane1.svg"
export const PLANE2_SVG = "/svg/plane2.svg"

export const LOADING_SVG = "/svg/loading.svg"
export const CHECK_SVG = "/svg/check.svg"
export const CLOSE_SVG = "/svg/close.svg"
export const CROSS_SVG = "/svg/cross.svg"
export const MENU_SVG = "/svg/menu.svg"
export const PACKAGE_SVG = "/svg/package.svg"
export const FLIGHT1_SVG = "/svg/flight1.svg"
export const LIKE_SVG = "/svg/like.svg"

// IMAGES
export const CTA_IMAGE = "/images/cta.webp"

export const BLOG_BANNER_IMAGE = "/images/blog-banner.webp"
export const TESTIMONIALS_BANNER_IMAGE = "/images/testimonials-banner.webp"

export const PAYMENT_APPROVED_BANNER_IMAGE =
	"/images/payment-approved-banner.webp"

export const HERO1_IMAGE = "/images/hero1.webp"
export const HERO2_IMAGE = "/images/hero2.webp"
export const HERO3_IMAGE = "/images/hero3.webp"
export const HERO4_IMAGE = "/images/hero4.webp"
export const HERO5_IMAGE = "/images/hero5.webp"
export const HERO6_IMAGE = "/images/hero6.webp"
export const HERO7_IMAGE = "/images/hero7.webp"
